### ISSUE TITLE
Check if UniqueAccount has a balance before getting it

### ISSUE THREAD

**Issue by CrazyPyroEagle** [hsyyid/AdminShop#6]
I'm using a custom economy plugin. Not all `UniqueAccount`s created by it have a balance for the default currency, which is why I must ask you to make more safety checks before trying to check if the account has enough money. If it does not have a balance for the currency, you should be able to instead set it to the default one +/- the amount you want to change its value.

On top of that, the account should check if it'll allow you to affect its balance (insufficient funds, account overflowing limit, etc...) and therefore you should not have to do the check yourself, just call `getResult` on the object the withdraw / deposit method returns.

**Comment by hsyyid** [comment]
Ok :)
